### ISSUE TITLE
middenGip is zowel pure-grid als flexbox. Waarom?

### ISSUE THREAD

**Issue by vbrh-immalle** [JelleS-immalle/jelles-immalle.github.io#5]

**Comment by JelleS-immalle** [comment]
Het enige dat ik kan vinden verwant aan flexbox bevindt zich in de class 'pure-g', wat een class is van pure-grid. Pure.css maakt dus ook gebruik van flexbox denk ik, als dat is wat u bedoelt?

**Comment by JelleS-immalle** [comment]
## Herinnering

+ MiddenGip-1-3 id veranderen naar class !id kan maar één keer gebruikt worden.
